### ISSUE TITLE
CSS custom properties should be vendor-prefixed

### ISSUE THREAD

**Issue by inoyakaigor** [sienori/simple-translate#83]
This properties can conflict with page css custom properties because its name is very common.

```css
:root {
    --main-text: #0c0c0d;
    --sub-text: #737373;
    --line: #ededf0;
    --button: #d7d7db;
    --highlight: #5595ff;
    --main-bg: #ffffff;
}
```
I think better way to prevent possible conflict with page is using vendor prefix like this:
```css
:root {
    --simple-translate-main-text: #0c0c0d;
    --simple-translate-sub-text: #737373;
    --simple-translate-line: #ededf0;
    --simple-translate-button: #d7d7db;
    --simple-translate-highlight: #5595ff;
    --simple-translate-main-bg: #ffffff;
}
```
